version: '3'
services:
  web:
    image: myapp/web:latest
    ports:
      - '3000:3000'
    depends_on:
      - api

  api:
    image: myapp/api:latest
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URI=mongodb://db:27017/mydatabase

  db:
    image: mongo:latest
    ports:
      - '27017:27017'